version: 2.1
jobs:
    build:
        docker:
            - image: nightscape/scala-mill
        steps:
            - checkout
            - run:
                name: Test 2.11.8
                command: mill "spark-constraints[2.11.8].test"
            - run:
                name: Test 2.12.4
                command: mill "spark-constraints[2.12.4].test"

